# .scrutinizer.yml
build:
    dependencies:
        before: 'composer install --dev --prefer-source'
    environment:
        php: '5.5.25'

checks:
    php:
        custom_coding_standard:
            ruleset_path: 'vendor/graze/standards/PHP/CodeSniffer/Graze/ruleset.xml'

tools:
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
